src/App.js, src/Login.js, src/Main.js, src/Success.js
Add some WIP samples to be continued by class
=> add rudimentary routing

package-lock.json, src/App.js, src/Login.js, src/LoginError.js, src/Main.js
=> add error route

package-lock.json, package.json, src/App.js, src/Header.js, src/Main.js
=> make header its own component

package-lock.json, src/Login.js, src/LoginError.js, src/Main.js, src/Signup.js, src/Success.js
Included Header component on all relevant components.
=> Header included

src/Signup.js
add function to submit signup form to node server
=> add fetch api for signup request

src/Login.js
=> add fetch api for login

src/Signup.js
disable submit at unverified passwords
=> feat: include formData instead of body

src/Signup.js
=> feat: add a read Password Must Match logic to button

src/Login.js, src/Section.js, src/Success.js
closes #33 
closes #31 
closes #36 
closes #35 
closes #34
=> 1.) fix login and success container styling to center main 2.) add reset password button 3.) add image to success (no image src sent yet)

src/ResetPassword.js, src/Signup.js
=> add useState w/hooks, remove classes

src/ChangePassword.js, src/Login.js
use hooks with functional components
=> update login, signup, reset with hooks

src/App.js, src/Header.js, src/Landing.js, src/Login.js, src/LoginError.js, src/ResetPassword.js, src/Signup.js, src/Success.js, src/index.css
- alter the button texts on various components
- add title props for each component
- convert switch into renderSwitch function
- reduce size of header title in css
- insert Header into ResetPassword with Back to Home button
closes #42 
closes #43 
closes #26
=> refactor: insert hooks into App and insert props to Components

src/App.js, src/Login.js, src/Success.js
display username selfie on success
closes #30
closes #29
=> Pass user selfie

public/manifest.json, src/App.js, src/Login.js
fixes #51 
fixes #52 
fixes #53
=> fix console errors

src/App.js, src/ChangePassword.js, src/Router.js
use location.history to update address bar for users
fixes #59 
fixes #57 
fixes #54 
fixes #58
=> add location/address bar functionality

src/App.js, src/ChangePassword.js, src/Router.js
use props for magic link, add fetch request to node server to invalidate magic link
=> add functionlaity to use magic llink as props

src/App.js, src/ChangePassword.js, src/Success.js
- add change password button to the success page
- add ternary variables to include full minutes and time of day
=> feat: check props for a user to display old password input

src/App.js, src/Router.js
- add resetRoute to add the route
closes #67
=> feat: alter the url to remove the double changePass

src/App.js, src/ChangePassword.js, src/Login.js
=> update users ability to update/forgot pw

src/ChangePassword.js
=> feat: encode the old and new passwords

src/App.js, src/ChangePassword.js, src/Login.js, src/Signup.js
closes #80 
closes #79 
closes #74 
closes #46 
closes #82
=> fix signup, reset nonauth user, redirects

package-lock.json, package.json, src/App.js, src/Login.js, src/ResetPassword.js
=> callback on reset pass

src/App.js, src/ChangePassword.js, src/Login.js, src/Signup.js, src/SignupStore.js, src/Success.js, src/UserStore.js
=> refactor: create user store and signup form store using Redux
